unit uJSONUser;

//  *************************************************
//    Generated By: JsonToDelphiClass - 0.65
//    Project link: https://github.com/PKGeorgiev/Delphi-JsonToDelphiClass
//    Generated On: 2020-03-30 14:23:29
//  *************************************************
//    Created By  : Petar Georgiev - 2014
//    WebSite     : http://pgeorgiev.com
//  *************************************************

interface

uses Generics.Collections, Rest.Json;

type

TUserClass = class
private
  FName: String;
  FPassword: String;
  FPath: String;
public
  property name: String read FName write FName;
  property password: String read FPassword write FPassword;
  property path: String read FPath write FPath;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TUserClass;
end;

TUsersClass = class
private
  FUser: TUserClass;
public
  property user: TUserClass read FUser write FUser;
  constructor Create;
  destructor Destroy; override;
  function ToJsonString: string;
  class function FromJsonString(AJsonString: string): TUsersClass;
end;

implementation

{TUserClass}


function TUserClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TUserClass.FromJsonString(AJsonString: string): TUserClass;
begin
  result := TJson.JsonToObject<TUserClass>(AJsonString)
end;

{TUsersClass}

constructor TUsersClass.Create;
begin
  inherited;
  FUser := TUserClass.Create();
end;

destructor TUsersClass.Destroy;
begin
  FUser.free;
  inherited;
end;

function TUsersClass.ToJsonString: string;
begin
  result := TJson.ObjectToJsonString(self);
end;

class function TUsersClass.FromJsonString(AJsonString: string): TUsersClass;
begin
  result := TJson.JsonToObject<TUsersClass>(AJsonString);
end;

end.

